# Generated by Django 3.1.13 on 2022-01-06 12:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('date_reported', models.DateTimeField(auto_now_add=True, null=True)),
                ('affected_population', models.PositiveIntegerField()),
                ('current_status', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Diseases',
            },
        ),
    ]
