# Generated by Django 3.1.13 on 2022-01-06 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both Male & Female', 'Both Male & Female')], max_length=50)),
                ('maximum_capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Hostel',
            },
        ),
        migrations.DeleteModel(
            name='Diseases',
        ),
    ]
